### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by iainbullock** [midstar/heatmiser_wifi_ha#4]
I've updated this to add some functionality and to support the PRT-HW model. 

Do you want me to submit a PR and merge, or as this project is deprecated shall I take over responsibiity for maintenance (not that I expect much)?

I also need to submit a PR to your underlying library https://github.com/midstar/heatmiser_wifi to support the new features. I see this is not deprecated.

Suggestion: You continue to maintain https://github.com/midstar/heatmiser_wifi and I take over https://github.com/midstar/heatmiser_wifi_ha

Let me know what you think / prefer

**Comment by midstar** [comment]
Hi,

Your suggestion sounds good to me. Please submit your PR to heatmiser_wifi.
I will not be able to test it because I don't own a Heatmiser thermostat
any more (mine was broken and replaced with other brands).

BR,
Joel

Den sön 5 maj 2024 kl 08:52 skrev Iain Bullock ***@***.***>:

**Comment by iainbullock** [comment]
Ok great. I will work on it over the course of this week

**Comment by iainbullock** [comment]
Thanks for merging my PR into your https://github.com/midstar/heatmiser_wifi 

Please could you make a minor update this project to:

- Link to my version as the live project: https://github.com/iainbullock/heatmiser_wifi_ha
- Update your hacs.json to maybe specify a different name in HACS (as our versions currently have the same name: e.g. "name": "Heatmiser Wifi - deprecated"). You might have a better way of dealing with this, maybe it can be deleted from HACS
- Consider archiving it so you don't get any new Issues (unlikely I agree)

Thanks a lot

**Comment by midstar** [comment]
Hi,

I have fixed bullet 1 and 2.

Let's try this out. In a couple of months I will archive (or remove) the
repository.

BR,
Joel

Den lör 11 maj 2024 kl 09:00 skrev Iain Bullock ***@***.***>:

**Comment by iainbullock** [comment]
Many thanks

Iain
